In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/results.csv')
display(df)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [5]:
#Pivot table:
df_pivot = pd.pivot_table(df,
                          values= 'place',
                          index=['discipline', 'event'],
                          columns=['noc', 'medal'],
                          fill_value=0)
display(df_pivot)

noc                                                                        AFG  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        AHO  \
medal                                                                   Silver
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        ALG  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                           \
medal                                                                   Gold
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)             0.0
                               3-on-3 Ice Hockey, Girls (YOG)            0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)             0.0
                               3x3 Basketball, Women (Olympic)           0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                      0.0
...                                                                      ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)    0.0
                               Welterweight, Greco-Roman, Men (Olympic)  0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)     0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)     0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)    0.0

noc                                                                             \
medal                                                                   Silver
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        AND  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        ANZ  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                           \
medal                                                                   Gold
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)             0.0
                               3-on-3 Ice Hockey, Girls (YOG)            0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)             0.0
                               3x3 Basketball, Women (Olympic)           0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                      0.0
...                                                                      ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)    0.0
                               Welterweight, Greco-Roman, Men (Olympic)  0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)     0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)     0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)    0.0

noc                                                                             \
medal                                                                   Silver
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        ARG  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                      ...  \
medal                                                                    ...
discipline                     event                                     ...
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)             ...
                               3-on-3 Ice Hockey, Girls (YOG)            ...
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)             ...
                               3x3 Basketball, Women (Olympic)           ...
Alpine Skiing (Skiing)         Combined, Boys (YOG)                      ...
...                                                                      ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)    ...
                               Welterweight, Greco-Roman, Men (Olympic)  ...
                               ≤46 kilograms, Freestyle, Girls (YOG)     ...
                               ≤70 kilograms, Freestyle, Girls (YOG)     ...
                               ≤85 kilograms, Greco Roman, Boys (YOG)    ...

noc                                                                        VIE  \
medal                                                                   Silver
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        WIF  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        YUG  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      3.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                           \
medal                                                                   Gold
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)             0.0
                               3-on-3 Ice Hockey, Girls (YOG)            0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)             0.0
                               3x3 Basketball, Women (Olympic)           0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                      0.0
...                                                                      ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)    0.0
                               Welterweight, Greco-Roman, Men (Olympic)  0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)     0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)     0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)    0.0

noc                                                                             \
medal                                                                   Silver
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        ZAM  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                             \
medal                                                                   Silver
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0
                               ≤46 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤70 kilograms, Freestyle, Girls (YOG)       0.0
                               ≤85 kilograms, Greco Roman, Boys (YOG)      0.0

noc                                                                        ZIM  \
medal                                                                   Bronze
discipline                     event
3-on-3 Ice Hockey (Ice Hockey) 3-on-3 Ice Hockey, Boys (YOG)               0.0
                               3-on-3 Ice Hockey, Girls (YOG)              0.0
3x3 Basketball (Basketball)    3x3 Basketball, Men (Olympic)               0.0
                               3x3 Basketball, Women (Olympic)             0.0
Alpine Skiing (Skiing)         Combined, Boys (YOG)                        0.0
...                                                                        ...
Wrestling                      Welterweight, Freestyle, Men (Olympic)      0.0
                               Welterweight, Greco-Roman, Men (Olympic)    0.0

In [19]:
#melt: It's used to convert columns into rows, basically reduce the width of the table and make it long. It's reverse of pivot.
df_melt = pd.melt(df,
    id_vars=['noc', 'discipline', 'event'],
    value_vars=['place'],
    var_name='Event',
    value_name='standing'
    )
display(df_melt)

,noc,discipline,event,Event,standing
0,FRA,Tennis,"Singles, Men (Olympic)",place,17.0
1,FRA,Tennis,"Doubles, Men (Olympic)",place,NaN
2,FRA,Tennis,"Singles, Men (Olympic)",place,32.0
3,FRA,Tennis,"Doubles, Mixed (Olympic)",place,8.0
4,FRA,Tennis,"Doubles, Men (Olympic)",place,4.0
...,...,...,...,...,...
308403,SVK,Luge,"Singles, Men (Olympic)",place,26.0
308404,SWE,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",place,28.0
308405,SWE,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",place,13.0
308406,SWE,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",place,NaN
308407,NaN,NaN,"Slalom, Women (Olympic)",place,24.0

In [ ]:
#stack: It's a reshaping function. It's used to convert columns into rows.
df_stack = df.stack()
display(df_stack)

#unstack: It's reverse of stack. It converts rows into individual rows.
df_unstack = df_stack.unstack()
display(df_unstack)

#explode: It's a reshaping function, which creates new rows for list type values in column. So if a column contains values which are list(multiple values), if we apply explore, it will create individual rows for each of the values in thje column.
df_explore = df1.explode()
display(df_explode)

0       year                          1912.0
        type                          Summer
        discipline                    Tennis
        event         Singles, Men (Olympic)
        as             Jean-François Blanchy
                               ...
308407  noc                              NaN
        team                             NaN
        place                           24.0
        tied                           False
        medal                            NaN
Length: 3392488, dtype: object

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN